# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/PROJECTS/Image-Processing/Pic-Simias/design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(210, 0, 741, 551))
        self.label_image.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_image.setStyleSheet("background-color:#e1e1e1")
        self.label_image.setText("")
        self.label_image.setScaledContents(False)
        self.label_image.setObjectName("label_image")
        self.properties = QtWidgets.QGroupBox(self.centralwidget)
        self.properties.setEnabled(True)
        self.properties.setGeometry(QtCore.QRect(10, 280, 191, 271))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.properties.setFont(font)
        self.properties.setObjectName("properties")
        self.rangeRow1 = QtWidgets.QSpinBox(self.properties)
        self.rangeRow1.setGeometry(QtCore.QRect(210, 110, 61, 20))
        self.rangeRow1.setMaximum(1200)
        self.rangeRow1.setObjectName("rangeRow1")
        self.rangeRow2 = QtWidgets.QSpinBox(self.properties)
        self.rangeRow2.setGeometry(QtCore.QRect(210, 140, 61, 20))
        self.rangeRow2.setObjectName("rangeRow2")
        self.rotationDial = QtWidgets.QDial(self.properties)
        self.rotationDial.setGeometry(QtCore.QRect(260, 20, 91, 71))
        self.rotationDial.setMaximum(360)
        self.rotationDial.setObjectName("rotationDial")
        self.zoomSlider = QtWidgets.QSlider(self.properties)
        self.zoomSlider.setEnabled(True)
        self.zoomSlider.setGeometry(QtCore.QRect(410, 150, 91, 22))
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setObjectName("zoomSlider")
        self.zoomLabel = QtWidgets.QLabel(self.properties)
        self.zoomLabel.setGeometry(QtCore.QRect(370, 150, 31, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.zoomLabel.setFont(font)
        self.zoomLabel.setObjectName("zoomLabel")
        self.rotateLabel = QtWidgets.QLabel(self.properties)
        self.rotateLabel.setGeometry(QtCore.QRect(220, 40, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rotateLabel.setFont(font)
        self.rotateLabel.setObjectName("rotateLabel")
        self.rowLabel = QtWidgets.QLabel(self.properties)
        self.rowLabel.setGeometry(QtCore.QRect(210, 90, 71, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rowLabel.setFont(font)
        self.rowLabel.setObjectName("rowLabel")
        self.columnLabel = QtWidgets.QLabel(self.properties)
        self.columnLabel.setGeometry(QtCore.QRect(280, 90, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.columnLabel.setFont(font)
        self.columnLabel.setObjectName("columnLabel")
        self.rangeCol2 = QtWidgets.QSpinBox(self.properties)
        self.rangeCol2.setGeometry(QtCore.QRect(290, 140, 61, 20))
        self.rangeCol2.setObjectName("rangeCol2")
        self.rangeCol1 = QtWidgets.QSpinBox(self.properties)
        self.rangeCol1.setGeometry(QtCore.QRect(290, 110, 61, 20))
        self.rangeCol1.setObjectName("rangeCol1")
        self.averageSlider = QtWidgets.QSlider(self.properties)
        self.averageSlider.setGeometry(QtCore.QRect(410, 30, 91, 22))
        self.averageSlider.setMinimum(1)
        self.averageSlider.setMaximum(15)
        self.averageSlider.setSingleStep(2)
        self.averageSlider.setProperty("value", 1)
        self.averageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.averageSlider.setObjectName("averageSlider")
        self.averageLabel = QtWidgets.QLabel(self.properties)
        self.averageLabel.setGeometry(QtCore.QRect(360, 30, 41, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.averageLabel.setFont(font)
        self.averageLabel.setObjectName("averageLabel")
        self.gaussianLabel = QtWidgets.QLabel(self.properties)
        self.gaussianLabel.setGeometry(QtCore.QRect(360, 60, 51, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gaussianLabel.setFont(font)
        self.gaussianLabel.setObjectName("gaussianLabel")
        self.gaussianSlider = QtWidgets.QSlider(self.properties)
        self.gaussianSlider.setGeometry(QtCore.QRect(410, 60, 91, 22))
        self.gaussianSlider.setMinimum(1)
        self.gaussianSlider.setMaximum(15)
        self.gaussianSlider.setSingleStep(2)
        self.gaussianSlider.setProperty("value", 1)
        self.gaussianSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussianSlider.setObjectName("gaussianSlider")
        self.medianLabel = QtWidgets.QLabel(self.properties)
        self.medianLabel.setGeometry(QtCore.QRect(360, 120, 41, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.medianLabel.setFont(font)
        self.medianLabel.setObjectName("medianLabel")
        self.medianSlider = QtWidgets.QSlider(self.properties)
        self.medianSlider.setGeometry(QtCore.QRect(410, 120, 91, 22))
        self.medianSlider.setMinimum(1)
        self.medianSlider.setMaximum(15)
        self.medianSlider.setSingleStep(2)
        self.medianSlider.setProperty("value", 1)
        self.medianSlider.setOrientation(QtCore.Qt.Horizontal)
        self.medianSlider.setObjectName("medianSlider")
        self.bilateralLabel = QtWidgets.QLabel(self.properties)
        self.bilateralLabel.setGeometry(QtCore.QRect(360, 90, 41, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.bilateralLabel.setFont(font)
        self.bilateralLabel.setObjectName("bilateralLabel")
        self.bilateralSlider = QtWidgets.QSlider(self.properties)
        self.bilateralSlider.setGeometry(QtCore.QRect(410, 90, 91, 22))
        self.bilateralSlider.setMinimum(1)
        self.bilateralSlider.setMaximum(15)
        self.bilateralSlider.setSingleStep(2)
        self.bilateralSlider.setOrientation(QtCore.Qt.Horizontal)
        self.bilateralSlider.setObjectName("bilateralSlider")
        self.sobelXcheckBox = QtWidgets.QCheckBox(self.properties)
        self.sobelXcheckBox.setGeometry(QtCore.QRect(570, 30, 61, 21))
        self.sobelXcheckBox.setObjectName("sobelXcheckBox")
        self.sobelYcheckBox = QtWidgets.QCheckBox(self.properties)
        self.sobelYcheckBox.setGeometry(QtCore.QRect(640, 30, 71, 21))
        self.sobelYcheckBox.setObjectName("sobelYcheckBox")
        self.sobelLabel = QtWidgets.QLabel(self.properties)
        self.sobelLabel.setGeometry(QtCore.QRect(530, 30, 31, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sobelLabel.setFont(font)
        self.sobelLabel.setObjectName("sobelLabel")
        self.cannyCheckBox = QtWidgets.QCheckBox(self.properties)
        self.cannyCheckBox.setGeometry(QtCore.QRect(530, 60, 131, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cannyCheckBox.setFont(font)
        self.cannyCheckBox.setObjectName("cannyCheckBox")
        self.laplacianCheckbox = QtWidgets.QCheckBox(self.properties)
        self.laplacianCheckbox.setGeometry(QtCore.QRect(530, 80, 71, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.laplacianCheckbox.setFont(font)
        self.laplacianCheckbox.setObjectName("laplacianCheckbox")
        self.resizeByRow = QtWidgets.QSpinBox(self.properties)
        self.resizeByRow.setGeometry(QtCore.QRect(290, 190, 51, 22))
        self.resizeByRow.setMinimum(5)
        self.resizeByRow.setMaximum(551)
        self.resizeByRow.setObjectName("resizeByRow")
        self.resizeByCol = QtWidgets.QSpinBox(self.properties)
        self.resizeByCol.setGeometry(QtCore.QRect(210, 190, 51, 22))
        self.resizeByCol.setMinimum(5)
        self.resizeByCol.setMaximum(741)
        self.resizeByCol.setObjectName("resizeByCol")
        self.resizeWidthLabel = QtWidgets.QLabel(self.properties)
        self.resizeWidthLabel.setGeometry(QtCore.QRect(210, 170, 47, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resizeWidthLabel.setFont(font)
        self.resizeWidthLabel.setObjectName("resizeWidthLabel")
        self.resizeHeightLabel = QtWidgets.QLabel(self.properties)
        self.resizeHeightLabel.setGeometry(QtCore.QRect(290, 170, 47, 13))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resizeHeightLabel.setFont(font)
        self.resizeHeightLabel.setObjectName("resizeHeightLabel")
        self.globalThresholdCheckbox = QtWidgets.QCheckBox(self.properties)
        self.globalThresholdCheckbox.setGeometry(QtCore.QRect(530, 100, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.globalThresholdCheckbox.setFont(font)
        self.globalThresholdCheckbox.setObjectName("globalThresholdCheckbox")
        self.meanThresholdCheckbox = QtWidgets.QCheckBox(self.properties)
        self.meanThresholdCheckbox.setGeometry(QtCore.QRect(530, 120, 111, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.meanThresholdCheckbox.setFont(font)
        self.meanThresholdCheckbox.setObjectName("meanThresholdCheckbox")
        self.gaussianThresholdCheckbox = QtWidgets.QCheckBox(self.properties)
        self.gaussianThresholdCheckbox.setGeometry(QtCore.QRect(530, 140, 121, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.gaussianThresholdCheckbox.setFont(font)
        self.gaussianThresholdCheckbox.setObjectName("gaussianThresholdCheckbox")
        self.cancelLinkButton = QtWidgets.QCommandLinkButton(self.properties)
        self.cancelLinkButton.setGeometry(QtCore.QRect(210, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(False)
        font.setWeight(50)
        self.cancelLinkButton.setFont(font)
        self.cancelLinkButton.setObjectName("cancelLinkButton")
        self.histogramEqlCheckBox = QtWidgets.QCheckBox(self.properties)
        self.histogramEqlCheckBox.setGeometry(QtCore.QRect(530, 160, 141, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.histogramEqlCheckBox.setFont(font)
        self.histogramEqlCheckBox.setObjectName("histogramEqlCheckBox")
        self.claheCheckBox = QtWidgets.QCheckBox(self.properties)
        self.claheCheckBox.setGeometry(QtCore.QRect(530, 180, 261, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.claheCheckBox.setFont(font)
        self.claheCheckBox.setObjectName("claheCheckBox")
        self.erosionLabel = QtWidgets.QLabel(self.properties)
        self.erosionLabel.setGeometry(QtCore.QRect(360, 180, 41, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.erosionLabel.setFont(font)
        self.erosionLabel.setObjectName("erosionLabel")
        self.dilationLabel = QtWidgets.QLabel(self.properties)
        self.dilationLabel.setGeometry(QtCore.QRect(360, 210, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dilationLabel.setFont(font)
        self.dilationLabel.setObjectName("dilationLabel")
        self.erosionSlider = QtWidgets.QSlider(self.properties)
        self.erosionSlider.setGeometry(QtCore.QRect(410, 180, 91, 22))
        self.erosionSlider.setMinimum(1)
        self.erosionSlider.setMaximum(5)
        self.erosionSlider.setSingleStep(2)
        self.erosionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.erosionSlider.setObjectName("erosionSlider")
        self.dilationSlider = QtWidgets.QSlider(self.properties)
        self.dilationSlider.setGeometry(QtCore.QRect(410, 210, 91, 22))
        self.dilationSlider.setMinimum(1)
        self.dilationSlider.setMaximum(5)
        self.dilationSlider.setSingleStep(2)
        self.dilationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dilationSlider.setObjectName("dilationSlider")
        self.openingLabel = QtWidgets.QLabel(self.properties)
        self.openingLabel.setGeometry(QtCore.QRect(530, 210, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.openingLabel.setFont(font)
        self.openingLabel.setObjectName("openingLabel")
        self.openingSlider = QtWidgets.QSlider(self.properties)
        self.openingSlider.setGeometry(QtCore.QRect(580, 210, 91, 22))
        self.openingSlider.setMinimum(1)
        self.openingSlider.setMaximum(5)
        self.openingSlider.setSingleStep(2)
        self.openingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.openingSlider.setObjectName("openingSlider")
        self.closingLabel = QtWidgets.QLabel(self.properties)
        self.closingLabel.setGeometry(QtCore.QRect(530, 240, 51, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.closingLabel.setFont(font)
        self.closingLabel.setObjectName("closingLabel")
        self.closingSlider = QtWidgets.QSlider(self.properties)
        self.closingSlider.setGeometry(QtCore.QRect(580, 240, 91, 22))
        self.closingSlider.setMinimum(1)
        self.closingSlider.setMaximum(5)
        self.closingSlider.setSingleStep(2)
        self.closingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.closingSlider.setObjectName("closingSlider")
        self.stopBtn = QtWidgets.QCommandLinkButton(self.properties)
        self.stopBtn.setGeometry(QtCore.QRect(10, 30, 131, 41))
        self.stopBtn.setObjectName("stopBtn")
        self.toolBox = QtWidgets.QTreeWidget(self.centralwidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 0, 191, 271))
        self.toolBox.setObjectName("toolBox")
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.toolBox)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 956, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.properties.setTitle(_translate("MainWindow", "Controls"))
        self.zoomLabel.setText(_translate("MainWindow", "Zoom"))
        self.rotateLabel.setText(_translate("MainWindow", "Rotate"))
        self.rowLabel.setText(_translate("MainWindow", "Row Range"))
        self.columnLabel.setText(_translate("MainWindow", "Columns Range"))
        self.averageLabel.setText(_translate("MainWindow", "Average"))
        self.gaussianLabel.setText(_translate("MainWindow", "Gaussian"))
        self.medianLabel.setText(_translate("MainWindow", "Medain"))
        self.bilateralLabel.setText(_translate("MainWindow", "Bilateral"))
        self.sobelXcheckBox.setText(_translate("MainWindow", "X-axis"))
        self.sobelYcheckBox.setText(_translate("MainWindow", "Y-axis"))
        self.sobelLabel.setText(_translate("MainWindow", "Sobel"))
        self.cannyCheckBox.setText(_translate("MainWindow", "Canny Edge Detector"))
        self.laplacianCheckbox.setText(_translate("MainWindow", "Laplacian"))
        self.resizeWidthLabel.setText(_translate("MainWindow", "Width"))
        self.resizeHeightLabel.setText(_translate("MainWindow", "Height"))
        self.globalThresholdCheckbox.setText(_translate("MainWindow", "Global Threshold"))
        self.meanThresholdCheckbox.setText(_translate("MainWindow", "Mean Threshold"))
        self.gaussianThresholdCheckbox.setText(_translate("MainWindow", "Gaussian Threshold"))
        self.cancelLinkButton.setText(_translate("MainWindow", "Cancel"))
        self.histogramEqlCheckBox.setText(_translate("MainWindow", "Histogram equalization"))
        self.claheCheckBox.setText(_translate("MainWindow", "Contrast Limited Adaptive HE"))
        self.erosionLabel.setText(_translate("MainWindow", "Erosion"))
        self.dilationLabel.setText(_translate("MainWindow", "Dilation"))
        self.openingLabel.setText(_translate("MainWindow", "Opening"))
        self.closingLabel.setText(_translate("MainWindow", "Closing"))
        self.stopBtn.setText(_translate("MainWindow", "STOP"))
        self.toolBox.headerItem().setText(0, _translate("MainWindow", "Toolbox"))
        __sortingEnabled = self.toolBox.isSortingEnabled()
        self.toolBox.setSortingEnabled(False)
        self.toolBox.topLevelItem(0).setText(0, _translate("MainWindow", "Basic Edits"))
        self.toolBox.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Zoom"))
        self.toolBox.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Rotate"))
        self.toolBox.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Crop"))
        self.toolBox.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Resize"))
        self.toolBox.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "Grayscale"))
        self.toolBox.topLevelItem(1).setText(0, _translate("MainWindow", "Blur & Noise"))
        self.toolBox.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Averaging"))
        self.toolBox.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "Gaussian"))
        self.toolBox.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "Median"))
        self.toolBox.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "Bilateral"))
        self.toolBox.topLevelItem(2).setText(0, _translate("MainWindow", "Edge Detection"))
        self.toolBox.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Laplacian"))
        self.toolBox.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Canny"))
        self.toolBox.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Sobel"))
        self.toolBox.topLevelItem(3).setText(0, _translate("MainWindow", "Thresholding"))
        self.toolBox.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "Global Threshold"))
        self.toolBox.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "Mean Threshold"))
        self.toolBox.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "Gaussian Threshold"))
        self.toolBox.topLevelItem(4).setText(0, _translate("MainWindow", "Arithmetic Operations"))
        self.toolBox.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "Blending"))
        self.toolBox.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "Bitwise"))
        self.toolBox.topLevelItem(5).setText(0, _translate("MainWindow", "Histogram Equalization"))
        self.toolBox.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "HE"))
        self.toolBox.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "CLAHE"))
        self.toolBox.topLevelItem(6).setText(0, _translate("MainWindow", "Morphological Transformation"))
        self.toolBox.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "Erosion"))
        self.toolBox.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "Dilation"))
        self.toolBox.topLevelItem(6).child(2).setText(0, _translate("MainWindow", "Opening"))
        self.toolBox.topLevelItem(6).child(3).setText(0, _translate("MainWindow", "Closing"))
        self.toolBox.topLevelItem(7).setText(0, _translate("MainWindow", "Face Recognition"))
        self.toolBox.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "Webcam"))
        self.toolBox.topLevelItem(7).child(1).setText(0, _translate("MainWindow", "Video"))
        self.toolBox.topLevelItem(7).child(2).setText(0, _translate("MainWindow", "Image"))
        self.toolBox.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

